data_files: [
    '/local1/rwadhawan/document_understanding/datasets/instruction_tune/scanned_documents/train.jsonl',
    '/local1/rwadhawan/document_understanding/datasets/instruction_tune/scanned_documents/dev.jsonl'
    # 'sft_v0.1_train.jsonl',
    # 'sft_v0.1_dev.jsonl'
]

train_processors: {
  sft: {type: 'CaptionProcessor', image_size: 224, min_scale: 0.5, randaug: False}
}

valid_processors: {
  sft: {type: 'DefaultProcessor', image_size: 224}
}

training_stage : 2